---
image_validating_webhook_enabled: true
image_validating_webhook_namespace: "registry-system"
image_validating_webhook_target_port: "8443"
image_validating_webhook_image_repo: "{{ docker_image_repo }}/tmaxcloudck/image-validation-webhook"
image_validating_webhook_image_tag: v5.0.4
image_validating_webhook_role_name: "image-validation-webhook-role"
image_validating_webhook_SA_name: "image-validation-webhook"
