---
- import_tasks: 0010-update-api-server.yml
  when:
    - dns_mode != 'none'
    - api_server_dns_cfwhn
  tags:
    - dns-policy-cfwhn

- import_tasks: delete-scheduler-port.yml
  when:
    - scheduler_port_0 == false
  tags:
    - scheduler-port

- import_tasks: delete-controller-manager-port.yml
  when:
    - controller_manager_port_0 == false
  tags:
    - controller-manager-port
