- name: Disable existing repositories
  shell: sed -i "s/enabled=1/enabled=0/g" /etc/yum.repos.d/*

- name: Add httpd repository setting to hosts
  template:
    src: files-repo.repo.j2
    dest: /etc/yum.repos.d/files-repo.repo
    mode: '0644'
    owner: root
    group: root

